name: Build armbian + companion

on:
  workflow_dispatch:
    inputs:
      armbian-url:
        type: string
        description: Armbian FW URL (Ubuntu minimal)
        default: 'https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.3_Orangepizero2_jammy_legacy_4.9.318.img.xz'
      companion-branch:
        type: choice
        description: Companion branch
        default: 'master'
        required: true
        options:
          - stable
          - beta
          - experimental

jobs:
  pi-img:
    runs-on: ubuntu-latest
    name: build image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: build image
        run: |
          sudo packer init companion.pkr.hcl
          sudo packer build -var "url=${{ github.event.inputs.armbian-url }}" -var "branch=${{ github.event.inputs.companion-branch }}" companion.pkr.hcl
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: compress image
        shell: bash
        run: |
          cd output-companion

          sudo apt-get install -y zerofree
          device="$(sudo losetup --partscan --show --find armbian-companion.img)"
          sudo zerofree "${device}p1"
          sudo losetup --detach "$device"

          sudo gzip -n armbian-companion.img
          originalname=$(basename ${{ github.event.inputs.armbian-url }} .img.xz)
          DATE=$(date +"%Y-%m-%d")
          targetname=${originalname}-companion-${DATE}-${{ github.run_id }}.img.gz
          sudo mv armbian-companion.img.gz ${targetname}

      - name: Upload Armbian image
        uses: actions/upload-artifact@v3
        with:
          name: Armbian_firmware
          path: output-companion/*